name: exfai
description: Exfai Ecommerce
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  auto_animated: ^3.0.1
  badges: ^3.1.1
  bd_l10n: ^1.2.0
  cached_network_image: ^3.2.0
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dropdown_search: ^5.0.6
  firebase_core: ^2.11.0
  firebase_messaging: ^14.5.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.3.1
  flutter_local_notifications: ^14.0.0+1
  flutter_localization: ^0.1.11
  flutter_localized_locales: ^2.0.4
  flutter_otp_text_field: ^1.0.1
  flutter_polyline_points: ^1.0.0
  flutter_ringtone_player: ^3.2.0
  flutter_screenutil: ^5.8.2
  flutter_svg: ^2.0.5
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.1.0
  geocoding: ^2.0.4
  geolocator: ^9.0.2
  get: ^4.6.1
  google_maps_flutter: ^2.3.0
  google_sign_in: ^6.1.0
  grouped_list: ^5.1.2
  http: ^0.13.4
  image_picker: ^0.8.7+4
  image_pickers: ^2.0.0+2
  intl: ^0.18.0
  jiffy: ^6.2.1
  lottie: ^2.3.2
  path: ^1.8.0
  qr_flutter: ^4.0.0
  rating_dialog: ^2.0.4
  rename: ^2.1.1
  responsive_builder: ^0.7.0
  scan: ^1.6.0
  shared_preferences: ^2.0.15
  show_up_animation: ^2.0.0
  sqflite: ^2.0.2
  timelines: ^0.1.0
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/avatar.png
    - assets/lottie/
    - assets/svg/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
